name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY }}  # Uses the encoded signing key stored in GitHub Secrets.
      run: |
        echo $ENCODED_STRING | base64 -di > app/scrcpy.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleScrcpyRelease
      env:
        SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload Signed Release APK
      uses: actions/upload-artifact@v4
      with:
        name: ScrcpyForAndroid-signed-release
        path: |
          app/build/outputs/apk/scrcpy/release/*.apk
        retention-days: 90  # Sets the artifact retention period to 90 days.
